### ISSUE TITLE
Is it possible to retrieve CPU vendor?

### ISSUE THREAD

**Issue by reagentoo** [jesusdf/grub-msr#2]
Hi. Is it possible to retrieve CPU vendor (Intel/AMD)?

**Comment by jesusdf** [comment]
You would have to use the cpuid instruction, GRUB has implemented a cpuid module already, although it doesn't have that feature (you can modify it yourself and send a patch to the GRUB project if you are interested).

https://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/commands/i386/cpuid.c?h=grub-2.06

https://lists.gnu.org/mailman/listinfo/grub-devel

https://en.wikipedia.org/wiki/CPUID
