### ISSUE TITLE
How to install for grub2?

### ISSUE THREAD

**Issue by proneon267** [jesusdf/grub-msr#3]
Using the install script in grub2 produces the following errors:
```cp: target '/boot/grub/i386-pc/' is not a directory
cat: /boot/grub/i386-pc/command.lst: No such file or directory
./install.sh: line 9: /boot/grub/i386-pc/command.lst: No such file or directory
./install.sh: line 10: /boot/grub/i386-pc/command.lst: No such file or directory
./install.sh: line 22: update-grub: command not found
```

Is there a different way to install the modules in grub2?

**Comment by jesusdf** [comment]
It's already included in upstream GRUB 2.04 and later, you don't have to use this repository (as stated in the README.md).

**Comment by proneon267** [comment]
I am using grub 2.06 rc1, but in grub command prompt, I get ```can't find command 'rdmsr'```. My secure boot is also off and I have checked and found ```lockdown``` variable was not set, as mentioned here: https://www.gnu.org/software/grub/manual/grub/html_node/rdmsr.html

**Comment by jesusdf** [comment]
Have you tried loading the module first?

insmod rdmsr
insmod wrmsr

Then the command should work. If it doesn't, maybe that grub version was built without it. You can check if the module is present with the following command:

ls -l /boot/grub/i386-pc/??msr.*

**Comment by proneon267** [comment]
When I try to load the module manually, grub still complains rdmsr.mod and wrmsr.mod are not present. Also, after checking the grub folder, the module files are really not present. So, indeed my grub was not built with rdmsr and wrmsr modules. I will try to install grub from upstream. Thanks for helping :)
